container:
  image: cirrusci/flutter:stable
  cpu: 1
  memory: 2G

task:
  name: Test
  get_script: flutter pub get
  test_script: flutter test --machine > report.json
  report_artifacts:
    path: report.json
    format: flutter
